### ISSUE TITLE
7) 1.b) Extend Your Repositories

### ISSUE THREAD

**Issue by Caro-ITU** [ITU-BDSA2024-GROUP24/Chirp#44]

**Comment by BBSITU** [comment]
Find Author by name, Find Author by email, Create a new Author er allerede lavet af Caro og Xander da de updaterede databasen. 

Create a new cheep. Er også lavet. men mangler at implementere: Note, that might mean to also create a respective author if she does not exist yet in Chirp!.

If not implemented already, retrieve cheeps for a certain page., If not implemented already, retrieve cheeps for a certain page that are written by a certain Author who is identified by name. Disse to mangler også at blive lavet.
