### ISSUE TITLE
9) Add feature:  Send Cheeps

### ISSUE THREAD

**Issue by Caro-ITU** [ITU-BDSA2024-GROUP24/Chirp#58]
- Extend chirp so users can send cheeps.
- Only users that are authenticated should be able to send cheeps(after login)
- Constrain Length of Cheeps
- Add UI Tests
- Add End-to-end Tests

Checkout chirp.core 
- [ ] cheepDTO same as Cheep ? contain the same classes 

Checkout chirp-infrastructure
- [ ] delete aplicationUser - it is redundant

**Comment by BBSITU** [comment]
Keep in mind to look to "Security Harden your application"
As written in the decription: Now, that you accept cheeps from users, make sure that your Chirp! application is not susceptible to cross-site scripting (XSS) or SQL injection attacks, 
we can see chapters 29.1 and 29.4.2 in the course book Andrew Lock ASP.NET Core in Action, Third Edition.

**Comment by BBSITU** [comment]
Vi starter på sending cheeps og kigger videre med de andre senere da login har en relevans til sending cheeps.
