### ISSUE TITLE
Add feature: Follow user

### ISSUE THREAD

**Issue by FrederikBorg** [ITU-BDSA2024-GROUP24/Chirp#59]
Add a feature such that a user can add other users to their own timeline.
This would probably include finding a way to add the user to the "find cheeps by author" that are displayed in the users own timeline:

- [x] Able to add more than one user to find by author
- [x] Add logic for adding and removing followed users
- [x] Add button for follow and unfollow
- [ ] Add test for all above

**Comment by BBSITU** [comment]
For the Html:
- [ ] public: make so there is a follow butten
- [ ] Public: if followed make so there is unfollow butten 
- [ ] usertimeline: make cheeps from followed visable on mytimeline 
- [ ] usertimeline: make unfollow butten visble on the followed cheeps

**Comment by Caro-ITU** [comment]
To start up Follow feature

- [ ] Make follow repository 
- [ ] Follow Interface 
- [ ] Add FollowDTO to chirp.core
- [ ] Add skeleton for follow functions/methods in repo
- [ ] Work on html (look at BBS comment)

**Comment by FrederikBorg** [comment]
The test requirement is also in Develop Test: Playwright test. therefore this is closed but the task remains
