### ISSUE TITLE
2.d) Refactor CLI interface - Proper parsing BBS/CSJ

### ISSUE THREAD

**Issue by Caro-ITU** [ITU-BDSA2024-GROUP24/Chirp#8]
Proper parsing of arguments and options that are provided to a program is difficult and error prone. Therefore, refactor your current Program.cs so that arguments passed to the program are not manually parsed out of the args property.

You may want to choose [System.CommandLine](https://learn.microsoft.com/en-us/archive/msdn-magazine/2019/march/net-parse-the-command-line-with-system-commandline), [CommandLine](https://github.com/commandlineparser/commandline), [docopt.net](https://docopt.github.io/docopt.net/dev/), or any other comparable library that you find on [nuget.org](https://www.nuget.org/).

**Comment by FrederikBorg** [comment]
Looking into doing it with Docopt
